"""
Configuration constants for the Humanoid Robot Warehouse System.
"""

# Robot Configuration
ROBOT_INITIAL_BATTERY = 100.0
ROBOT_BATTERY_CRITICAL = 5
ROBOT_BATTERY_CHARGING_THRESHOLD = 20
ROBOT_BATTERY_RETRIEVAL_COST = 7.0
ROBOT_BATTERY_PACKING_COST = 5.0
ROBOT_BATTERY_NAVIGATION_COST = 2.0
ROBOT_CHARGING_TIME = 3.0

# Navigation Configuration
NAVIGATION_OBSTACLE_CHANCE = 0.2
NAVIGATION_REROUTE_FAILURE_CHANCE = 0.01
NAVIGATION_HOME_LOCATION = "Robot station"
NAVIGATION_CHARGING_STATION = "CHARGING_STATION"
NAVIGATION_TIME_PER_MOVE = 2.0

# Sensor Configuration
SENSOR_FAILURE_RATE = 0.01
SENSOR_SCAN_TIME = 1.0

# Gripper Configuration
GRIPPER_PICK_TIME = 1.5
GRIPPER_DROP_TIME = 1.0

# Packing Configuration
PACKING_TIME_PER_ITEM = 2.0

# System Configuration
MAX_ITEMS_PER_ORDER = 100
MAX_ITEM_WEIGHT = 1000.0
MIN_ITEM_WEIGHT = 0.01

# Robot Modes
MODE_FULL_AUTO = "FULL_AUTO"
MODE_SEMI_AUTO = "SEMI_AUTO"
